LANGUAGES = {
    'en': {'name': 'English', 'flag': '🇬🇧'},
    'ru': {'name': 'Русский', 'flag': '🇷🇺'},
    'es': {'name': 'Español', 'flag': '🇪🇸'},
    'fr': {'name': 'Français', 'flag': '🇫🇷'},
    'de': {'name': 'Deutsch', 'flag': '🇩🇪'},
    'zh': {'name': '中文', 'flag': '🇨🇳'},
    'ja': {'name': '日本語', 'flag': '🇯🇵'},
    'ko': {'name': '한국어', 'flag': '🇰🇷'},
    'it': {'name': 'Italiano', 'flag': '🇮🇹'},
    'pt': {'name': 'Português', 'flag': '🇵🇹'},
}

LOCALES = {
    'en': {
        # Welcome & Setup
        'welcome': 'Welcome to Ollama Client bot! Please enter your Ollama client IP and port in the format: http://ip:port',
        'invalid_host': 'Invalid format. Please use the format: http://ip:port (e.g., http://192.168.1.1:11434)',
        'enter_new_host': 'Please enter your new Ollama host in the format: http://ip:port',
        
        # Main Menu
        'main_menu': '📋 Main Menu',
        'selected_model': 'Selected model',
        'no_model': 'No model selected',
        
        # Buttons
        'btn_model_select': '🤖 Select Model',
        'btn_new_chat': '💬 New Chat',
        'btn_chats': '📚 My Chats',
        'btn_settings': '⚙️ Settings',
        'btn_add_model': '➕ Add Model',
        'btn_back': '🔙 Back',
        'btn_create_chat': '➕ Create Chat',
        'btn_delete_chat': '🗑 Delete Chat',
        'btn_rename_chat': '✏️ Rename Chat',
        'btn_continue_chat': '💬 Continue Chat',
        'btn_change_host': '🔄 Change Host',
        'btn_manage_hosts': '📡 Manage Hosts',
        'btn_add_host': '➕ Add Host',
        'btn_select_translator': '🌐 Select Translator',
        'btn_manage_models': '📦 Manage Models',
        'btn_localization': '🌍 Language',
        'btn_none': '❌ None',
        'btn_regenerate': '🔄 Regenerate',
        'btn_modify': '✏️ Modify',
        'btn_shorter': '📉 Shorter',
        'btn_longer': '📈 Longer',
        'btn_simpler': '😊 Simpler',
        'btn_complex': '🎓 More Complex',
        'btn_edit_response': '✍️ Edit Response',
        
        # Model Selection
        'model_selection': '🤖 Model Selection',
        'enter_model_name': 'Enter model name (e.g., qwen2.5:3b or deepseek-r1). You can find models at ollama.com',
        'downloading_model': '⬇️ Downloading model...',
        'model_downloaded': '✅ Model successfully downloaded!',
        'model_not_found': '❌ Model not found. Please check the name and try again.',
        'loading_model': '⏳ Loading model...',
        'model_loaded': '✅ Model loaded!',
        'model_load_error': '❌ Error loading model',
        'unloading_model': '⏳ Unloading model...',
        'model_unloaded': '✅ Model unloaded',
        'model_unload_error': '❌ Error unloading model',
        
        # Chats
        'new_chat_name': 'New Chat',
        'chat_with_model': '💬 Chat with model',
        'no_chats': 'You haven\'t created any chats yet.',
        'your_chats': '📚 Your Chats',
        'chat': 'Chat',
        'model_in_chat': 'Model',
        'chat_deleted': '🗑 Chat deleted',
        'enter_new_name': 'Enter new chat name:',
        'chat_renamed': '✅ Chat renamed',
        'continuing_chat': '💬 Continuing chat',
        
        # Settings
        'settings': '⚙️ Settings',
        'selected_host': 'Selected host',
        'translator_model': 'Translator model',
        'loaded_models': 'Loaded models',
        'none': 'None',
        'select_translator_model': '🌐 Select translator model',
        'translator_set': '✅ Translator model set',
        'manage_models_text': '📦 Model Management\n\n📥 - Load model\n📤 - Unload model',
        'select_language': '🌍 Select Language',
        'language_changed': '✅ Language changed',
        
        # Messages
        'please_select_model': '⚠️ Please select a model first',
        'error_generating': '❌ Error generating response',
        'error_translating': '❌ Error translating',
        'enter_new_response': 'Enter your new version of the response:',
        'response_updated': '✅ Response updated',
        
        # Inline Mode
        'no_model_selected': 'No model selected',
        'please_select_model_inline': 'Please select a model in the bot first',
        'inline_answer': '💬 Answer',
        'inline_answer_desc': 'Get AI response to your query',
        'inline_translate': '🌐 Translate',
        'inline_translate_desc': 'Translate your text',
        'no_translator': '⚠️ Translator model not configured',
    },
    
    'ru': {
        # Welcome & Setup
        'welcome': 'Добро пожаловать в бот Ollama Client! Введите IP и порт вашего клиента Ollama в формате: http://ip:port',
        'invalid_host': 'Неверный формат. Используйте формат: http://ip:port (например, http://192.168.1.1:11434)',
        'enter_new_host': 'Введите новый хост Ollama в формате: http://ip:port',
        
        # Main Menu
        'main_menu': '📋 Главное меню',
        'selected_model': 'Выбранная модель',
        'no_model': 'Модель не выбрана',
        
        # Buttons
        'btn_model_select': '🤖 Выбор модели',
        'btn_new_chat': '💬 Новый чат',
        'btn_chats': '📚 Список чатов',
        'btn_settings': '⚙️ Настройки',
        'btn_add_model': '➕ Добавить модель',
        'btn_back': '🔙 Назад',
        'btn_create_chat': '➕ Создать чат',
        'btn_delete_chat': '🗑 Удалить чат',
        'btn_rename_chat': '✏️ Изменить название',
        'btn_continue_chat': '💬 Продолжить общение',
        'btn_change_host': '🔄 Изменить хост',
        'btn_manage_hosts': '📡 Управление хостами',
        'btn_add_host': '➕ Добавить хост',
        'btn_select_translator': '🌐 Выбрать переводчик',
        'btn_manage_models': '📦 Управление моделями',
        'btn_localization': '🌍 Язык',
        'btn_none': '❌ Нет',
        'btn_regenerate': '🔄 Перегенерировать',
        'btn_modify': '✏️ Изменить',
        'btn_shorter': '📉 Короче',
        'btn_longer': '📈 Длиннее',
        'btn_simpler': '😊 Проще',
        'btn_complex': '🎓 Сложнее',
        'btn_edit_response': '✍️ Редактировать ответ',
        
        # Model Selection
        'model_selection': '🤖 Выбор модели',
        'enter_model_name': 'Напишите название модели (например, qwen2.5:3b или deepseek-r1). Список моделей можно найти на ollama.com',
        'downloading_model': '⬇️ Загрузка модели...',
        'model_downloaded': '✅ Модель успешно загружена!',
        'model_not_found': '❌ Модель не найдена. Проверьте название и попробуйте снова.',
        'loading_model': '⏳ Загрузка модели...',
        'model_loaded': '✅ Модель загружена!',
        'model_load_error': '❌ Ошибка загрузки модели',
        'unloading_model': '⏳ Выгрузка модели...',
        'model_unloaded': '✅ Модель выгружена',
        'model_unload_error': '❌ Ошибка выгрузки модели',
        
        # Chats
        'new_chat_name': 'Новый чат',
        'chat_with_model': '💬 Вы в чате с моделью',
        'no_chats': 'Вы еще не создали ни одного чата.',
        'your_chats': '📚 Ваши чаты',
        'chat': 'Чат',
        'model_in_chat': 'Модель в чате',
        'chat_deleted': '🗑 Чат удален',
        'enter_new_name': 'Введите новое название чата:',
        'chat_renamed': '✅ Чат переименован',
        'continuing_chat': '💬 Продолжаем чат',
        
        # Settings
        'settings': '⚙️ Настройки',
        'selected_host': 'Выбранный хост',
        'translator_model': 'Модель-переводчик',
        'loaded_models': 'Загруженные модели',
        'none': 'Нет',
        'select_translator_model': '🌐 Выберите модель-переводчик',
        'translator_set': '✅ Модель-переводчик установлена',
        'manage_models_text': '📦 Управление моделями\n\n📥 - Загрузить модель\n📤 - Выгрузить модель',
        'select_language': '🌍 Выберите язык',
        'language_changed': '✅ Язык изменен',
        
        # Messages
        'please_select_model': '⚠️ Сначала выберите модель',
        'error_generating': '❌ Ошибка генерации ответа',
        'error_translating': '❌ Ошибка перевода',
        'enter_new_response': 'Введите новую версию ответа:',
        'response_updated': '✅ Ответ обновлен',
        
        # Inline Mode
        'no_model_selected': 'Модель не выбрана',
        'please_select_model_inline': 'Сначала выберите модель в боте',
        'inline_answer': '💬 Ответить',
        'inline_answer_desc': 'Получить ответ ИИ на ваш запрос',
        'inline_translate': '🌐 Перевести',
        'inline_translate_desc': 'Перевести ваш текст',
        'no_translator': '⚠️ Модель-переводчик не настроена',
    },
    
    'es': {
        'welcome': '¡Bienvenido al bot de Ollama Client! Ingrese su IP y puerto del cliente Ollama en el formato: http://ip:puerto',
        'invalid_host': 'Formato inválido. Use el formato: http://ip:puerto (ej., http://192.168.1.1:11434)',
        'enter_new_host': 'Ingrese su nuevo host de Ollama en el formato: http://ip:puerto',
        'main_menu': '📋 Menú Principal',
        'selected_model': 'Modelo seleccionado',
        'no_model': 'Ningún modelo seleccionado',
        'btn_model_select': '🤖 Seleccionar Modelo',
        'btn_new_chat': '💬 Nuevo Chat',
        'btn_chats': '📚 Mis Chats',
        'btn_settings': '⚙️ Configuración',
        'btn_add_model': '➕ Añadir Modelo',
        'btn_back': '🔙 Atrás',
        'btn_create_chat': '➕ Crear Chat',
        'btn_delete_chat': '🗑 Eliminar Chat',
        'btn_rename_chat': '✏️ Renombrar Chat',
        'btn_continue_chat': '💬 Continuar Chat',
        'btn_change_host': '🔄 Cambiar Host',
        'btn_select_translator': '🌐 Seleccionar Traductor',
        'btn_manage_models': '📦 Gestionar Modelos',
        'btn_localization': '🌍 Idioma',
        'btn_none': '❌ Ninguno',
        'btn_regenerate': '🔄 Regenerar',
        'btn_modify': '✏️ Modificar',
        'btn_shorter': '📉 Más Corto',
        'btn_longer': '📈 Más Largo',
        'btn_simpler': '😊 Más Simple',
        'btn_complex': '🎓 Más Complejo',
        'btn_edit_response': '✍️ Editar Respuesta',
        'model_selection': '🤖 Selección de Modelo',
        'enter_model_name': 'Ingrese el nombre del modelo (ej., qwen2.5:3b o deepseek-r1). Puede encontrar modelos en ollama.com',
        'downloading_model': '⬇️ Descargando modelo...',
        'model_downloaded': '✅ ¡Modelo descargado exitosamente!',
        'model_not_found': '❌ Modelo no encontrado. Verifique el nombre e intente nuevamente.',
        'loading_model': '⏳ Cargando modelo...',
        'model_loaded': '✅ ¡Modelo cargado!',
        'model_load_error': '❌ Error al cargar el modelo',
        'unloading_model': '⏳ Descargando modelo...',
        'model_unloaded': '✅ Modelo descargado',
        'model_unload_error': '❌ Error al descargar el modelo',
        'new_chat_name': 'Nuevo Chat',
        'chat_with_model': '💬 Chat con el modelo',
        'no_chats': 'Aún no has creado ningún chat.',
        'your_chats': '📚 Tus Chats',
        'chat': 'Chat',
        'model_in_chat': 'Modelo',
        'chat_deleted': '🗑 Chat eliminado',
        'enter_new_name': 'Ingrese nuevo nombre del chat:',
        'chat_renamed': '✅ Chat renombrado',
        'continuing_chat': '💬 Continuando chat',
        'settings': '⚙️ Configuración',
        'selected_host': 'Host seleccionado',
        'translator_model': 'Modelo traductor',
        'loaded_models': 'Modelos cargados',
        'none': 'Ninguno',
        'select_translator_model': '🌐 Seleccione modelo traductor',
        'translator_set': '✅ Modelo traductor configurado',
        'manage_models_text': '📦 Gestión de Modelos\n\n📥 - Cargar modelo\n📤 - Descargar modelo',
        'select_language': '🌍 Seleccionar Idioma',
        'language_changed': '✅ Idioma cambiado',
        'please_select_model': '⚠️ Seleccione primero un modelo',
        'error_generating': '❌ Error al generar respuesta',
        'error_translating': '❌ Error al traducir',
        'enter_new_response': 'Ingrese su nueva versión de la respuesta:',
        'response_updated': '✅ Respuesta actualizada',
        'no_model_selected': 'Ningún modelo seleccionado',
        'please_select_model_inline': 'Seleccione primero un modelo en el bot',
        'inline_answer': '💬 Responder',
        'inline_answer_desc': 'Obtener respuesta de IA a su consulta',
        'inline_translate': '🌐 Traducir',
        'inline_translate_desc': 'Traducir su texto',
        'no_translator': '⚠️ Modelo traductor no configurado',
    },
    
    'fr': {
        'welcome': 'Bienvenue dans le bot Ollama Client! Veuillez entrer votre IP et port du client Ollama au format: http://ip:port',
        'invalid_host': 'Format invalide. Utilisez le format: http://ip:port (ex., http://192.168.1.1:11434)',
        'enter_new_host': 'Veuillez entrer votre nouvel hôte Ollama au format: http://ip:port',
        'main_menu': '📋 Menu Principal',
        'selected_model': 'Modèle sélectionné',
        'no_model': 'Aucun modèle sélectionné',
        'btn_model_select': '🤖 Sélectionner Modèle',
        'btn_new_chat': '💬 Nouveau Chat',
        'btn_chats': '📚 Mes Chats',
        'btn_settings': '⚙️ Paramètres',
        'btn_add_model': '➕ Ajouter Modèle',
        'btn_back': '🔙 Retour',
        'btn_create_chat': '➕ Créer Chat',
        'btn_delete_chat': '🗑 Supprimer Chat',
        'btn_rename_chat': '✏️ Renommer Chat',
        'btn_continue_chat': '💬 Continuer Chat',
        'btn_change_host': '🔄 Changer Hôte',
        'btn_select_translator': '🌐 Sélectionner Traducteur',
        'btn_manage_models': '📦 Gérer Modèles',
        'btn_localization': '🌍 Langue',
        'btn_none': '❌ Aucun',
        'btn_regenerate': '🔄 Régénérer',
        'btn_modify': '✏️ Modifier',
        'btn_shorter': '📉 Plus Court',
        'btn_longer': '📈 Plus Long',
        'btn_simpler': '😊 Plus Simple',
        'btn_complex': '🎓 Plus Complexe',
        'btn_edit_response': '✍️ Modifier Réponse',
        'model_selection': '🤖 Sélection de Modèle',
        'enter_model_name': 'Entrez le nom du modèle (ex., qwen2.5:3b ou deepseek-r1). Vous pouvez trouver des modèles sur ollama.com',
        'downloading_model': '⬇️ Téléchargement du modèle...',
        'model_downloaded': '✅ Modèle téléchargé avec succès!',
        'model_not_found': '❌ Modèle non trouvé. Vérifiez le nom et réessayez.',
        'loading_model': '⏳ Chargement du modèle...',
        'model_loaded': '✅ Modèle chargé!',
        'model_load_error': '❌ Erreur de chargement du modèle',
        'unloading_model': '⏳ Déchargement du modèle...',
        'model_unloaded': '✅ Modèle déchargé',
        'model_unload_error': '❌ Erreur de déchargement du modèle',
        'new_chat_name': 'Nouveau Chat',
        'chat_with_model': '💬 Chat avec le modèle',
        'no_chats': 'Vous n\'avez pas encore créé de chats.',
        'your_chats': '📚 Vos Chats',
        'chat': 'Chat',
        'model_in_chat': 'Modèle',
        'chat_deleted': '🗑 Chat supprimé',
        'enter_new_name': 'Entrez le nouveau nom du chat:',
        'chat_renamed': '✅ Chat renommé',
        'continuing_chat': '💬 Poursuite du chat',
        'settings': '⚙️ Paramètres',
        'selected_host': 'Hôte sélectionné',
        'translator_model': 'Modèle traducteur',
        'loaded_models': 'Modèles chargés',
        'none': 'Aucun',
        'select_translator_model': '🌐 Sélectionner modèle traducteur',
        'translator_set': '✅ Modèle traducteur configuré',
        'manage_models_text': '📦 Gestion des Modèles\n\n📥 - Charger modèle\n📤 - Décharger modèle',
        'select_language': '🌍 Sélectionner Langue',
        'language_changed': '✅ Langue changée',
        'please_select_model': '⚠️ Veuillez d\'abord sélectionner un modèle',
        'error_generating': '❌ Erreur de génération de réponse',
        'error_translating': '❌ Erreur de traduction',
        'enter_new_response': 'Entrez votre nouvelle version de la réponse:',
        'response_updated': '✅ Réponse mise à jour',
        'no_model_selected': 'Aucun modèle sélectionné',
        'please_select_model_inline': 'Veuillez d\'abord sélectionner un modèle dans le bot',
        'inline_answer': '💬 Répondre',
        'inline_answer_desc': 'Obtenir une réponse IA à votre requête',
        'inline_translate': '🌐 Traduire',
        'inline_translate_desc': 'Traduire votre texte',
        'no_translator': '⚠️ Modèle traducteur non configuré',
    },
    
    'de': {
        'welcome': 'Willkommen beim Ollama Client Bot! Bitte geben Sie Ihre Ollama-Client-IP und -Port im Format ein: http://ip:port',
        'invalid_host': 'Ungültiges Format. Verwenden Sie das Format: http://ip:port (z.B. http://192.168.1.1:11434)',
        'enter_new_host': 'Bitte geben Sie Ihren neuen Ollama-Host im Format ein: http://ip:port',
        'main_menu': '📋 Hauptmenü',
        'selected_model': 'Ausgewähltes Modell',
        'no_model': 'Kein Modell ausgewählt',
        'btn_model_select': '🤖 Modell Wählen',
        'btn_new_chat': '💬 Neuer Chat',
        'btn_chats': '📚 Meine Chats',
        'btn_settings': '⚙️ Einstellungen',
        'btn_add_model': '➕ Modell Hinzufügen',
        'btn_back': '🔙 Zurück',
        'btn_create_chat': '➕ Chat Erstellen',
        'btn_delete_chat': '🗑 Chat Löschen',
        'btn_rename_chat': '✏️ Chat Umbenennen',
        'btn_continue_chat': '💬 Chat Fortsetzen',
        'btn_change_host': '🔄 Host Ändern',
        'btn_select_translator': '🌐 Übersetzer Wählen',
        'btn_manage_models': '📦 Modelle Verwalten',
        'btn_localization': '🌍 Sprache',
        'btn_none': '❌ Keine',
        'btn_regenerate': '🔄 Regenerieren',
        'btn_modify': '✏️ Ändern',
        'btn_shorter': '📉 Kürzer',
        'btn_longer': '📈 Länger',
        'btn_simpler': '😊 Einfacher',
        'btn_complex': '🎓 Komplexer',
        'btn_edit_response': '✍️ Antwort Bearbeiten',
        'model_selection': '🤖 Modellauswahl',
        'enter_model_name': 'Geben Sie den Modellnamen ein (z.B. qwen2.5:3b oder deepseek-r1). Modelle finden Sie auf ollama.com',
        'downloading_model': '⬇️ Modell wird heruntergeladen...',
        'model_downloaded': '✅ Modell erfolgreich heruntergeladen!',
        'model_not_found': '❌ Modell nicht gefunden. Überprüfen Sie den Namen und versuchen Sie es erneut.',
        'loading_model': '⏳ Modell wird geladen...',
        'model_loaded': '✅ Modell geladen!',
        'model_load_error': '❌ Fehler beim Laden des Modells',
        'unloading_model': '⏳ Modell wird entladen...',
        'model_unloaded': '✅ Modell entladen',
        'model_unload_error': '❌ Fehler beim Entladen des Modells',
        'new_chat_name': 'Neuer Chat',
        'chat_with_model': '💬 Chat mit Modell',
        'no_chats': 'Sie haben noch keine Chats erstellt.',
        'your_chats': '📚 Ihre Chats',
        'chat': 'Chat',
        'model_in_chat': 'Modell',
        'chat_deleted': '🗑 Chat gelöscht',
        'enter_new_name': 'Geben Sie den neuen Chat-Namen ein:',
        'chat_renamed': '✅ Chat umbenannt',
        'continuing_chat': '💬 Chat wird fortgesetzt',
        'settings': '⚙️ Einstellungen',
        'selected_host': 'Ausgewählter Host',
        'translator_model': 'Übersetzer-Modell',
        'loaded_models': 'Geladene Modelle',
        'none': 'Keine',
        'select_translator_model': '🌐 Übersetzer-Modell wählen',
        'translator_set': '✅ Übersetzer-Modell festgelegt',
        'manage_models_text': '📦 Modellverwaltung\n\n📥 - Modell laden\n📤 - Modell entladen',
        'select_language': '🌍 Sprache Wählen',
        'language_changed': '✅ Sprache geändert',
        'please_select_model': '⚠️ Bitte wählen Sie zuerst ein Modell',
        'error_generating': '❌ Fehler beim Generieren der Antwort',
        'error_translating': '❌ Übersetzungsfehler',
        'enter_new_response': 'Geben Sie Ihre neue Version der Antwort ein:',
        'response_updated': '✅ Antwort aktualisiert',
        'no_model_selected': 'Kein Modell ausgewählt',
        'please_select_model_inline': 'Bitte wählen Sie zuerst ein Modell im Bot',
        'inline_answer': '💬 Antworten',
        'inline_answer_desc': 'KI-Antwort auf Ihre Anfrage erhalten',
        'inline_translate': '🌐 Übersetzen',
        'inline_translate_desc': 'Ihren Text übersetzen',
        'no_translator': '⚠️ Übersetzer-Modell nicht konfiguriert',
    },
}

# Fill in missing translations with English
for lang_code in LANGUAGES.keys():
    if lang_code not in LOCALES:
        LOCALES[lang_code] = LOCALES['en'].copy()
    else:
        for key in LOCALES['en'].keys():
            if key not in LOCALES[lang_code]:
                LOCALES[lang_code][key] = LOCALES['en'][key]
